version: '3.8'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/app
    env_file:
      - ./.env
